# Generated by Django 4.2 on 2023-05-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=50)),
                ('roman', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=50)),
                ('roman', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Year_of_engineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('abbrevation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=100)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.semester')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.year_of_engineering')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.batch')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.division')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.year_of_engineering')),
            ],
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_num', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
                ('assistant', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.batch')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Batch_Grp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.year_of_engineering')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_grp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.batch_grp'),
        ),
        migrations.AddField(
            model_name='batch',
            name='div',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.division'),
        ),
        migrations.AddField(
            model_name='batch',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.semester'),
        ),
        migrations.AddField(
            model_name='batch',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.year_of_engineering'),
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_performance', models.DateField()),
                ('date_of_submission', models.DateField()),
                ('RPP', models.IntegerField(default=0)),
                ('SPO', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('practical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.practical')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.student')),
            ],
        ),
    ]
