# Generated by Django 4.2 on 2023-05-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_batch_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='year',
        ),
    ]
