# Generated by Django 4.2 on 2023-05-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_remove_batch_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='div',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
