# Generated by Django 4.2 on 2023-05-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_student_div_remove_student_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='roman',
            new_name='num',
        ),
    ]
