# Generated by Django 4.2 on 2023-05-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_rename_roman_division_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='total',
        ),
    ]
